=== gotomahi/SwingXmlUI/config/screen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="property">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="name" use="optional"/>
          <xs:attribute type="xs:string" name="type" use="optional"/>
          <xs:attribute type="xs:string" name="dimension" use="optional"/>
          <xs:attribute type="xs:string" name="list" use="optional"/>
          <xs:attribute type="xs:string" name="inpageaction" use="optional"/>
          <xs:attribute type="xs:string" name="actionName" use="optional"/>
          <xs:attribute type="xs:string" name="default_value" use="optional"/>
          <xs:attribute type="xs:string" name="listeners" use="optional"/>
          <xs:attribute type="xs:string" name="labelProperty" use="optional"/>
          <xs:attribute type="xs:string" name="property" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="panel">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="node" minOccurs="0"/>
        <xs:element ref="PanelComponent" minOccurs="0"/>
        <xs:element ref="panel" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="dimension" use="optional"/>
      <xs:attribute type="xs:string" name="treepane" use="optional"/>
      <xs:attribute type="xs:short" name="divider_location" use="optional"/>
      <xs:attribute type="xs:string" name="border_left_title" use="optional"/>
      <xs:attribute type="xs:string" name="position" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="panel"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="optional"/>
      <xs:attribute type="xs:string" name="action" use="optional"/>
      <xs:attribute type="xs:string" name="border_left_title" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="node">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="node" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="action" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="optional"/>
      <xs:attribute type="xs:string" name="screen" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="action">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="name"/>
          <xs:attribute type="xs:string" name="image"/>
          <xs:attribute type="xs:string" name="description"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="PanelComponent">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="panel" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="dimension"/>
      <xs:attribute type="xs:string" name="list"/>
      <xs:attribute type="xs:string" name="type"/>
      <xs:attribute type="xs:string" name="name"/>
      <xs:attribute type="xs:string" name="border_left_title"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gotomahi/SwingXmlUI/src/com/gui/claim/payee.xml
<?xml version="1.0" encoding="UTF-8"?>
<page name="Customer" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com screen.xsd">
	<action>com.gui.claim.PayeeAction</action>
	<panel dimension="0,0,1,1,1.0,1.0,12,1,0,0,0,0">
		<property label="Payee" type="Label" position="0,0" size="80,25" />
		<property name="treeMap.claim.payee.payeeType" type="ComboBox" list="treeMap.PayeeTypes" default_value="--Please Select--" position="1,0" size="150,25" listeners="ActionListener"
			actionName="PayeeType" />
		<property label="Payee Name" type="Label" position="0,1" size="80,25" />
		<property name="treeMap.claim.payee.payeeName" type="TextField" position="1,1" size="150,25" />
		<property label="Dealer Code" type="Label" position="2,1" size="80,25" />
		<property name="treeMap.claim.payee.dealerCode" type="TextField" enable_expr="${treeMap.claim.payee.payeeType}=Dealer" position="3,1" size="150,25" />
		<property label="Transaction Ref" type="Label" position="0,2" size="80,25" />
		<property name="treeMap.claim.payee.transactionRef" type="TextField" position="1,2" size="150,25" />
		<property label="Bank Details1" type="Label" position="2,2" size="80,25" />
		<property name="treeMap.claim.payee.bankDetails1" type="TextField" position="3,2" size="150,25" />
		<property label="Bank Details2" type="Label" position="0,3" size="80,25" />
		<property name="treeMap.claim.payee.bankDetails2" type="TextField" position="1,3" size="150,25" />
		<property label="Bank Details3" type="Label" position="2,3" size="80,25" />
		<property name="treeMap.claim.payee.bankDetails3" type="TextField" position="3,3" size="150,25" />
		<property label="Bank Details4" type="Label" position="0,4" size="80,25" />
		<property name="treeMap.claim.payee.bankDetails4" type="TextField" position="1,4" size="150,25" />
		<property label="Address1" type="Label" position="2,4" size="80,25" />
		<property name="treeMap.claim.payee.address1" type="TextField" position="3,4" size="150,25" />
		<property label="Address2" type="Label" position="0,5" size="80,25" />
		<property name="treeMap.claim.payee.address2" type="TextField" position="1,5" size="150,25" />
		<property label="Address3" type="Label" position="2,5" size="80,25" />
		<property name="treeMap.claim.payee.address3" type="TextField" position="3,5" size="150,25" />
		<property label="Address4" type="Label" position="0,6" size="80,25" />
		<property name="treeMap.claim.payee.address4" type="TextField" position="1,6" size="150,25" />
	</panel>
</page>

=== gotomahi/SwingXmlUI/src/com/gui/policy/summary.xml
<?xml version="1.0" encoding="UTF-8"?>
<page name="PolicySummary" dialog="true" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com screen.xsd">
	<action>com.gui.policy.SummaryAction</action>
	<panel dimension="0,0,1,1,1.0,1.0,12,1,0,0,0,0">
		<property label="Title" type="Label" position="0,0" size="80,25" />
		<property property="treeMap.plan.customer.title" type="Label" position="1,0" size="150,25" />
		<property label="First Name" type="Label" position="0,1" size="80,25" />
		<property property="treeMap.plan.customer.firstName" type="Label" position="1,1" size="150,25" />
		<property label="Last Name" type="Label" position="2,1" size="80,25" />
		<property property="treeMap.plan.customer.lastName" type="Label" position="3,1" size="150,25" />
		<property label="Middle Name" type="Label" position="0,2" size="80,25" />
		<property property="treeMap.plan.customer.middleName" type="Label" position="1,2" size="150,25" />
		<property label="Email" type="Label" position="2,2" size="80,25" />
		<property property="treeMap.plan.customer.email" type="Label" position="3,2" size="150,25" />
	</panel>
	<panel dimension="0,1,1,1,1.0,1.0,18,1,0,0,0,0">
		<property label="Make" type="Label" position="0,0" size="80,25" />
		<property property="treeMap.MakeModel.make" type="Label" position="1,0" size="150,25" />
		<property label="Model" type="Label" position="2,0" size="80,25" />
		<property property="treeMap.MakeModel.model" type="Label" position="3,0" size="150,25" />
		<property label="VIN" type="Label" position="0,1" size="80,25" />
		<property property="treeMap.policyMap.vehicle.vin" type="Label" position="1,1" size="150,25" />
		<property label="Reg No" type="Label" position="2,1" size="80,25" />
		<property property="treeMap.policyMap.vehicle.regNo" type="Label" position="3,1" size="150,25" />
	</panel>
	<panel dimension="0,2,1,1,1.0,1.0,10,1,0,0,0,0">
		<property name="Confirm" type="Button" position="0,0" size="80,25" />
	</panel>
</page>
